name: Python Setup
runs:
  using: "composite" # <-- this is the important part
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Requirements
      shell: bash
      run: pip install -r requirements.txt -r requirements-test.txt
    - uses: reviewdog/action-setup@latest
      with:
        reviewdog_version: latest
