name: Python Formatting

on:
  - push

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup > isort.results
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run iSort
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          isort --extend-skip .venv/ --profile black --check-only . | reviewdog -f=isort -name="ISort Results" -reporter=github-check
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup
      - uses: reviewdog/action-setup@v1
      - name: Run Black
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          black --check --extend-exclude ".venv/" . | reviewdog -f=black -name="Black Results" -reporter=github-check
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup > flake8.results
      - uses: reviewdog/action-setup@v1
      - name: Run Flake8
        with:
          reviewdog_version: latest
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: flake8 --extend-exclude .venv/ . | reviewdog -f=flake8 -name="Flake8 Results" -reporter=github-check
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup
      - name: Run PyLint
      - uses: reviewdog/action-setup@v1
      - name: Run PyLint
        with:
          reviewdog_version: latest
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: flake8 --extend-exclude .venv/ . | reviewdog -f=flake8 -
        run: |
          pylint $(find -type f -name "*.py" ! -path "**/.venv/**") | reviewdog -efm="%f:%l:%c: %m" -name="PyLint Results" -reporter=github-check
