name: Python Setup
runs:
  using: "composite" # <-- this is the important part
  steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install REquirements
      run: pip install -r requirements.txt -r requirements-test.txt